name: CICD Pipeline (Java with Maven)

on:
  push:
    branches: [ "main" ]
    
jobs:

  compile:
    runs-on: ubuntu-latest
    #  runs-on: ubuntu-latest - This is a Shared Runner provided by GitHub

# Inside each job, there are multiple steps. 
# uses - actions 
# uses: actions/checkout@v4to setup an Env. On the runner it will create a Local Repo.
# Each step can have its own name
# Like:
  # - uses: actions/checkout@v4
  # - name: Set up JDK 17
   
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
