name: CICD Pipeline (Java with Maven)

on:
  push:
    branches: [ "main" ]
    
jobs:

  compile:
    # runs-on: self-hosted
    runs-on: v1
    #  runs-on: ubuntu-latest - This is a Shared Runner provided by GitHub

# Inside each job, there are multiple steps. 
# uses - actions 
# uses: actions/checkout@v4to setup an Env. On the runner it will create a Local Repo.
# Each step can have its own name
# Like:
  # - uses: actions/checkout@v4
  # - name: Set up JDK 17
   
    steps:
    - name: Checkout the Repo
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn compile

  security-check:
    # runs-on: self-hosted
    runs-on: v1
    needs: compile 
 
   
    steps:
    - name: Checkout the Repo
      uses: actions/checkout@v4

    - name: Trivy Installation
      run: |
        sudo apt-get install wget apt-transport-https gnupg lsb-release -y
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
        echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update -y
        sudo apt-get install trivy -y
        
    - name: Trivy Fs Scan
      run: |
        trivy fs --format table -o fs-report.json .

    - name: gitleak Installation
      run: |
        sudo apt install gitleaks -y

    - name: GitLeaks Code Scan
      run: |
        gitleaks detect soruce . -r gitleaks-report.json -f json
        
  test :
    # runs-on: self-hosted
    runs-on: v1
    needs: security-check

    steps:
    - name: Checkout the Repo
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Unit Test Cases
      run: mvn test

  sonar:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout the Repo
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build Project
      run: mvn package
        
    - name: Cache SOnar Package
      uses: actions/cache@v4
      with: 
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v2
      with:
          projectKey: Aashwin11_Project-GITHUB-ACTION-DevOpsShack
          organization: aashwin11
          
    - name: SonarCloud Quality Gate Check
      uses: sonarsource/sonarqube-quality-gate-action@master
      with:
        projectKey: Aashwin11_Project-GITHUB-ACTION-DevOpsShack
        organization: aashwin11
   
  
